import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Header from "@/components/Header";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "To-Do App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="fi">
            <body className={inter.className}>{children}</body>
        </html>
    );
}
