import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { auth } from "@/lib/auth";
import SessionProvider from "@/components/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "To-Do App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const session = await auth();

    return (
        <html lang="fi">
            <body
                className={`${inter.className} bg-ctp-base text-ctp-base-text`}
            >
                <SessionProvider session={session}>{children}</SessionProvider>
            </body>
        </html>
    );
}
