import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Header from "@/components/header";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "To-Do App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="fi">
            <body
                className={`${inter.className} bg-slate-300 flex flex-col min-h-screen`}
            >
                <Header />
                <main className="container mx-auto">{children}</main>
            </body>
        </html>
    );
}
